typography_spectrum: 0.24047900480218232
color:
  brandStrength: 0.9903458403423429
  lightness: 0.917744328500703
  saturation: 0.12227901257574558
  rhythmicContrast: 0.7567411581985652
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.5914188222959638
name: UnHushable
navigation:
  - name: Ossic headphones create 3D audio unique to you
    id: a938465e-d65d-48bf-8d3c-cccdd5f94366
    type: content
  - name: All the adults colouring is leading to huge sales for pencil companies
    id: d2c1ee92-09d7-4c6c-873e-688a79abd98d
    type: content
description: Shout!
